export const flags = {
    '🇦🇨': 'ASCENSION ISLAND',
    '🇦🇩': 'ANDORRA',
    '🇦🇪': 'UNITED ARAB EMIRATES',
    '🇦🇫': 'AFGHANISTAN',
    '🇦🇬': 'ANTIGUA & BARBUDA',
    '🇦🇮': 'ANGUILLA',
    '🇦🇱': 'ALBANIA',
    '🇦🇲': 'ARMENIA',
    '🇦🇴': 'ANGOLA',
    '🇦🇶': 'ANTARCTICA',
    '🇦🇷': 'ARGENTINA',
    '🇦🇸': 'AMERICAN SAMOA',
    '🇦🇹': 'AUSTRIA',
    '🇦🇺': 'AUSTRALIA',
    '🇦🇼': 'ARUBA',
    '🇦🇽': 'ÅLAND ISLANDS',
    '🇦🇿': 'AZERBAIJAN',
    '🇧🇦': 'BOSNIA & HERZEGOVINA',
    '🇧🇧': 'BARBADOS',
    '🇧🇩': 'BANGLADESH',
    '🇧🇪': 'BELGIUM',
    '🇧🇫': 'BURKINA FASO',
    '🇧🇬': 'BULGARIA',
    '🇧🇭': 'BAHRAIN',
    '🇧🇮': 'BURUNDI',
    '🇧🇯': 'BENIN',
    '🇧🇱': 'ST. BARTHÉLEMY',
    '🇧🇲': 'BERMUDA',
    '🇧🇳': 'BRUNEI',
    '🇧🇴': 'BOLIVIA',
    '🇧🇶': 'CARIBBEAN NETHERLANDS',
    '🇧🇷': 'BRAZIL',
    '🇧🇸': 'BAHAMAS',
    '🇧🇹': 'BHUTAN',
    '🇧🇻': 'BOUVET ISLAND',
    '🇧🇼': 'BOTSWANA',
    '🇧🇾': 'BELARUS',
    '🇧🇿': 'BELIZE',
    '🇨🇦': 'CANADA',
    '🇨🇨': 'COCOS (KEELING) ISLANDS',
    '🇨🇩': 'CONGO - KINSHASA',
    '🇨🇫': 'CENTRAL AFRICAN REPUBLIC',
    '🇨🇬': 'CONGO - BRAZZAVILLE',
    '🇨🇭': 'SWITZERLAND',
    '🇨🇮': 'CÔTE D’IVOIRE',
    '🇨🇰': 'COOK ISLANDS',
    '🇨🇱': 'CHILE',
    '🇨🇲': 'CAMEROON',
    '🇨🇳': 'CHINA',
    '🇨🇴': 'COLOMBIA',
    '🇨🇵': 'CLIPPERTON ISLAND',
    '🇨🇷': 'COSTA RICA',
    '🇨🇺': 'CUBA',
    '🇨🇻': 'CAPE VERDE',
    '🇨🇼': 'CURAÇAO',
    '🇨🇽': 'CHRISTMAS ISLAND',
    '🇨🇾': 'CYPRUS',
    '🇨🇿': 'CZECHIA',
    '🇩🇪': 'GERMANY',
    '🇩🇬': 'DIEGO GARCIA',
    '🇩🇯': 'DJIBOUTI',
    '🇩🇰': 'DENMARK',
    '🇩🇲': 'DOMINICA',
    '🇩🇴': 'DOMINICAN REPUBLIC',
    '🇩🇿': 'ALGERIA',
    '🇪🇦': 'CEUTA & MELILLA',
    '🇪🇨': 'ECUADOR',
    '🇪🇪': 'ESTONIA',
    '🇪🇬': 'EGYPT',
    '🇪🇭': 'WESTERN SAHARA',
    '🇪🇷': 'ERITREA',
    '🇪🇸': 'SPAIN',
    '🇪🇹': 'ETHIOPIA',
    // '🇪🇺': 'EUROPEAN UNION',
    '🇫🇮': 'FINLAND',
    '🇫🇯': 'FIJI',
    '🇫🇰': 'FALKLAND ISLANDS',
    '🇫🇲': 'MICRONESIA',
    '🇫🇴': 'FAROE ISLANDS',
    '🇫🇷': 'FRANCE',
    '🇬🇦': 'GABON',
    '🇬🇧': 'UNITED KINGDOM',
    '🇬🇩': 'GRENADA',
    '🇬🇪': 'GEORGIA',
    '🇬🇫': 'FRENCH GUIANA',
    '🇬🇬': 'GUERNSEY',
    '🇬🇭': 'GHANA',
    '🇬🇮': 'GIBRALTAR',
    '🇬🇱': 'GREENLAND',
    '🇬🇲': 'GAMBIA',
    '🇬🇳': 'GUINEA',
    '🇬🇵': 'GUADELOUPE',
    '🇬🇶': 'EQUATORIAL GUINEA',
    '🇬🇷': 'GREECE',
    '🇬🇸': 'SOUTH GEORGIA & SOUTH SANDWICH ISLANDS',
    '🇬🇹': 'GUATEMALA',
    '🇬🇺': 'GUAM',
    '🇬🇼': 'GUINEA-BISSAU',
    '🇬🇾': 'GUYANA',
    '🇭🇰': 'HONG KONG SAR CHINA',
    '🇭🇲': 'HEARD & MCDONALD ISLANDS',
    '🇭🇳': 'HONDURAS',
    '🇭🇷': 'CROATIA',
    '🇭🇹': 'HAITI',
    '🇭🇺': 'HUNGARY',
    '🇮🇨': 'CANARY ISLANDS',
    '🇮🇩': 'INDONESIA',
    '🇮🇪': 'IRELAND',
    '🇮🇱': 'ISRAEL',
    '🇮🇲': 'ISLE OF MAN',
    '🇮🇳': 'INDIA',
    '🇮🇴': 'BRITISH INDIAN OCEAN TERRITORY',
    '🇮🇶': 'IRAQ',
    '🇮🇷': 'IRAN',
    '🇮🇸': 'ICELAND',
    '🇮🇹': 'ITALY',
    '🇯🇪': 'JERSEY',
    '🇯🇲': 'JAMAICA',
    '🇯🇴': 'JORDAN',
    '🇯🇵': 'JAPAN',
    '🇰🇪': 'KENYA',
    '🇰🇬': 'KYRGYZSTAN',
    '🇰🇭': 'CAMBODIA',
    '🇰🇮': 'KIRIBATI',
    '🇰🇲': 'COMOROS',
    '🇰🇳': 'ST. KITTS & NEVIS',
    '🇰🇵': 'NORTH KOREA',
    '🇰🇷': 'SOUTH KOREA',
    '🇰🇼': 'KUWAIT',
    '🇰🇾': 'CAYMAN ISLANDS',
    '🇰🇿': 'KAZAKHSTAN',
    '🇱🇦': 'LAOS',
    '🇱🇧': 'LEBANON',
    '🇱🇨': 'ST. LUCIA',
    '🇱🇮': 'LIECHTENSTEIN',
    '🇱🇰': 'SRI LANKA',
    '🇱🇷': 'LIBERIA',
    '🇱🇸': 'LESOTHO',
    '🇱🇹': 'LITHUANIA',
    '🇱🇺': 'LUXEMBOURG',
    '🇱🇻': 'LATVIA',
    '🇱🇾': 'LIBYA',
    '🇲🇦': 'MOROCCO',
    '🇲🇨': 'MONACO',
    '🇲🇩': 'MOLDOVA',
    '🇲🇪': 'MONTENEGRO',
    '🇲🇫': 'ST. MARTIN',
    '🇲🇬': 'MADAGASCAR',
    '🇲🇭': 'MARSHALL ISLANDS',
    '🇲🇰': 'NORTH MACEDONIA',
    '🇲🇱': 'MALI',
    '🇲🇲': 'MYANMAR (BURMA)',
    '🇲🇳': 'MONGOLIA',
    '🇲🇴': 'MACAO SAR CHINA',
    '🇲🇵': 'NORTHERN MARIANA ISLANDS',
    '🇲🇶': 'MARTINIQUE',
    '🇲🇷': 'MAURITANIA',
    '🇲🇸': 'MONTSERRAT',
    '🇲🇹': 'MALTA',
    '🇲🇺': 'MAURITIUS',
    '🇲🇻': 'MALDIVES',
    '🇲🇼': 'MALAWI',
    '🇲🇽': 'MEXICO',
    '🇲🇾': 'MALAYSIA',
    '🇲🇿': 'MOZAMBIQUE',
    '🇳🇦': 'NAMIBIA',
    '🇳🇨': 'NEW CALEDONIA',
    '🇳🇪': 'NIGER',
    '🇳🇫': 'NORFOLK ISLAND',
    '🇳🇬': 'NIGERIA',
    '🇳🇮': 'NICARAGUA',
    '🇳🇱': 'NETHERLANDS',
    '🇳🇴': 'NORWAY',
    '🇳🇵': 'NEPAL',
    '🇳🇷': 'NAURU',
    '🇳🇺': 'NIUE',
    '🇳🇿': 'NEW ZEALAND',
    '🇴🇲': 'OMAN',
    '🇵🇦': 'PANAMA',
    '🇵🇪': 'PERU',
    '🇵🇫': 'FRENCH POLYNESIA',
    '🇵🇬': 'PAPUA NEW GUINEA',
    '🇵🇭': 'PHILIPPINES',
    '🇵🇰': 'PAKISTAN',
    '🇵🇱': 'POLAND',
    '🇵🇲': 'ST. PIERRE & MIQUELON',
    '🇵🇳': 'PITCAIRN ISLANDS',
    '🇵🇷': 'PUERTO RICO',
    '🇵🇸': 'PALESTINIAN TERRITORIES',
    '🇵🇹': 'PORTUGAL',
    '🇵🇼': 'PALAU',
    '🇵🇾': 'PARAGUAY',
    '🇶🇦': 'QATAR',
    '🇷🇪': 'RÉUNION',
    '🇷🇴': 'ROMANIA',
    '🇷🇸': 'SERBIA',
    '🇷🇺': 'RUSSIA',
    '🇷🇼': 'RWANDA',
    '🇸🇦': 'SAUDI ARABIA',
    '🇸🇧': 'SOLOMON ISLANDS',
    '🇸🇨': 'SEYCHELLES',
    '🇸🇩': 'SUDAN',
    '🇸🇪': 'SWEDEN',
    '🇸🇬': 'SINGAPORE',
    '🇸🇭': 'ST. HELENA',
    '🇸🇮': 'SLOVENIA',
    '🇸🇯': 'SVALBARD & JAN MAYEN',
    '🇸🇰': 'SLOVAKIA',
    '🇸🇱': 'SIERRA LEONE',
    '🇸🇲': 'SAN MARINO',
    '🇸🇳': 'SENEGAL',
    '🇸🇴': 'SOMALIA',
    '🇸🇷': 'SURINAME',
    '🇸🇸': 'SOUTH SUDAN',
    '🇸🇹': 'SÃO TOMÉ & PRÍNCIPE',
    '🇸🇻': 'EL SALVADOR',
    '🇸🇽': 'SINT MAARTEN',
    '🇸🇾': 'SYRIA',
    '🇸🇿': 'ESWATINI',
    '🇹🇦': 'TRISTAN DA CUNHA',
    '🇹🇨': 'TURKS & CAICOS ISLANDS',
    '🇹🇩': 'CHAD',
    '🇹🇫': 'FRENCH SOUTHERN TERRITORIES',
    '🇹🇬': 'TOGO',
    '🇹🇭': 'THAILAND',
    '🇹🇯': 'TAJIKISTAN',
    '🇹🇰': 'TOKELAU',
    '🇹🇱': 'TIMOR-LESTE',
    '🇹🇲': 'TURKMENISTAN',
    '🇹🇳': 'TUNISIA',
    '🇹🇴': 'TONGA',
    '🇹🇷': 'TURKEY',
    '🇹🇹': 'TRINIDAD & TOBAGO',
    '🇹🇻': 'TUVALU',
    '🇹🇼': 'TAIWAN',
    '🇹🇿': 'TANZANIA',
    '🇺🇦': 'UKRAINE',
    '🇺🇬': 'UGANDA',
    '🇺🇲': 'U.S. OUTLYING ISLANDS',
    // '🇺🇳': 'UNITED NATIONS',
    '🇺🇸': 'UNITED STATES',
    '🇺🇾': 'URUGUAY',
    '🇺🇿': 'UZBEKISTAN',
    '🇻🇦': 'VATICAN CITY',
    '🇻🇨': 'ST. VINCENT & GRENADINES',
    '🇻🇪': 'VENEZUELA',
    '🇻🇬': 'BRITISH VIRGIN ISLANDS',
    '🇻🇮': 'U.S. VIRGIN ISLANDS',
    '🇻🇳': 'VIETNAM',
    '🇻🇺': 'VANUATU',
    '🇼🇫': 'WALLIS & FUTUNA',
    '🇼🇸': 'SAMOA',
    '🇽🇰': 'KOSOVO',
    '🇾🇪': 'YEMEN',
    '🇾🇹': 'MAYOTTE',
    '🇿🇦': 'SOUTH AFRICA',
    '🇿🇲': 'ZAMBIA',
    '🇿🇼': 'ZIMBABWE',
    // '🏴󠁧󠁢󠁥󠁮󠁧󠁿': 'ENGLAND',
    // '🏴󠁧󠁢󠁳󠁣󠁴󠁿': 'SCOTLAND',
    // '🏴󠁧󠁢󠁷󠁬󠁳󠁿': 'WALES'
};
